### PR TITLE
Scram

### PR DESCRIPTION
**Pull request by squ1d123**

### CODE REVIEW

**Comment by squ1d123** [comment]
This will address issue <https://github.com/danielqsj/kafka_exporter/issues/98>

**Comment by fritchie** [comment]
thx, looking forward to Scram support

**Comment by fritchie** [comment]
thx, looking forward to this

**Comment by gramer** [comment]
I've tried it, but the connection is very unstable.

` ./kafka_exporter  --kafka.server=xxxx:9092  --sasl.enabled --sasl.username=xxx --sasl.password="xxxx" --sasl.mechanism="scram-sha256" --kafka.version=2.1.0 --log.enable-sarama
`

The following logs are often visible and as a result collecting often fails.

`[sarama] 2019/04/28 11:11:01 SASL authentication failed not enough fields in first server message
[sarama] 2019/04/28 11:11:01 Closed connection to broker xxxx:9092
ERRO[0079] Cannot get current offset of topic kafka.qili-local.1 partition 0: not enough fields in first server message  source="kafka_exporter.go:290"
ERRO[0079] Cannot get current offset of topic kafka.test2.1 partition 0: not enough fields in first server message  source="kafka_exporter.go:290"
ERRO[0079] Cannot get current offset of topic message2_api.app_push_dispatcher.v1 partition 0: not enough fields in first server message  source="kafka_exporter.go:290"
ERRO[0079] Cannot get current offset of topic kafka.test-2.1 partition 0: not enough fields in first server message  source="kafka_exporter.go:290"
[sarama] 2019/04/28 11:11:01 SASL authentication failed error parsing 'r=MrRT9lQ8Cw8/uc6AKQUfWraadsOTD+Wt14hvfqsbdg5v4ebqhclog4jojs' for field 'e'
[sarama] 2019/04/28 11:11:01 Closed connection to broker xxx:9092
[sarama] 2019/04/28 11:11:01 client/metadata fetching metadata for [message2_api.text_dispatcher_response.v1] from broker xxx:9092
ERRO[0079] Cannot get current offset of topic kafka.test.1 partition 0: error parsing 'r=MrRT9lQ8Cw8/uc6AKQUfWraadsOTD+Wt14hvfqsbdg5v4ebqhclog4jojs' for field 'e'  source="kafka_exporter.go:290"`

image

**Comment by robholland** [comment]
This has worked great for us, no connection issues.

**Comment by gramer** [comment]
After upgrading sarama, no connection issue. refer to below commits
https://github.com/Shopify/sarama/pull/1349

**Comment by squ1d123** [comment]
Updated pull request to use latest sarama as referred to by @gramer

**Comment by peimanja** [comment]
Any update on this one?

**Comment by muffin87** [comment]
It would be wonderfull if this feature would be added. All my Kafka clusters need to use SCRAM.

**Comment by rajivchirania** [comment]
@squ1d123 How can i use your branch..I get the below error

Failed to pull image "squ1d123/kafka_exporter:latest": rpc error: code = Unknown desc = Error response from daemon: pull access denied for squ1d123/kafka_exporter, repository does not exist or may require 'docker login'

**Comment by fcosta-td** [comment]
Is something missing from this PR to prevent it from being merged?

**Comment by paulojmdias** [comment]
Can someone merge this? It works and we need that.

**Comment by Neustradamus** [comment]
Any news?

**Comment by leonrado** [comment]
Merge this will be great

**Comment by gabrielmuras** [comment]
Any news? Merging will be very helpful for us.

**Comment by jagdeepgithub** [comment]
Yes it would be helpful if we can merge this change. Thanks!

**Comment by Fanduzi** [comment]
@danielqsj 
合并分支吧, 现在很多公司都开SCRAM认证了. 这么多老外等着呢

**Comment by danielqsj** [comment]
Thanks @squ1d123 

/lgtm

**Comment by Neustradamus** [comment]
@Fanduzi, @danielqsj: Thanks a lot after one year for this PR!

**Comment by Neustradamus** [comment]
@squ1d123, @Fanduzi, @danielqsj: Thanks a lot after one year for this PR!

**Comment by jagdeepgithub** [comment]
Any eta on when this will be released?

**Comment by koflTS** [comment]
The merged commit does not build on Travis. I also have a need for this feature. Hopefully someone finds the error soon.

**Pull request merged**
