### PR TITLE
Performance improvements for large clusters

### PR DESCRIPTION
**Pull request by uepoch**
This should increase the performance a lot on large clusters

On our very heavy clusters (17k partitions ~) this reduced the time to get the full answer from 35 to 5s while also reducing the load on the cluster (we were aggressively scraping it) by around 40%

I can provide more information in private as theses metrics are sadly not publishable :)

Also added a singleflight like logic to avoid having multiple concurrent fetch of the cluster's state

### CODE REVIEW

**Comment by danielqsj** [comment]
@uepoch thanks, could you do a rebase ?

**Comment by turbotankist** [comment]
We need this update!

**Comment by uepoch** [comment]
I can, and I will, sorry I left that for so long :)

**Comment by uepoch** [comment]
Updated against master branch, will test again if the merge didn't break anything, should be safe tho

**Comment by uepoch** [comment]
@danielqsj @turbotankist

**Comment by Tahvok** [comment]
@danielqsj as mentioned in #171 we see a big improvement in performance. Please take a look at this.

**Comment by talonx** [comment]
Any chance of this getting merged soon?

**Comment by danielqsj** [comment]
hi everyone, @uepoch @Tahvok @talonx : to be honest, I'm very busy in other things, sorry for the late reply. Have you test this PR and running it for few days ? If there is no issues, I will merge it soon.

**Comment by Tahvok** [comment]
@danielqsj I'm running from my own branch #171  - but given it's the same work and it's running good for couple of months now, I think you can merge

**Comment by talonx** [comment]
@danielqsj This PR is working fine for me too.

**Comment by HimanshPal** [comment]
@danielqsj @Tahvok - can this we merged ?

**Comment by danielqsj** [comment]
@uepoch I have released 1.3.0. Sorry for missing this patch, could you do another rebase? I will merge it soon.

**Comment by alesj** [comment]
@danielqsj @uepoch 
* https://github.com/danielqsj/kafka_exporter/pull/213

**Comment by renemifsud** [comment]
@danielqsj by any chance do you have an ETA on when this will be merged please?

**Comment by danielqsj** [comment]
thanks @uepoch @alesj , I cherry-picked from #228, and released v1.4.1. @ALL, please have a try.

**Pull request closed without merging**
