### PR TITLE
Update readme for azure managed prometheus support

### PR DESCRIPTION
**Pull request by rashmichandrashekar**
Adding instructions in the readme section for azure managed prometheus

### CODE REVIEW

**Comment by rashmichandrashekar** [comment]
@danielqsj - Please take a look, thanks!

**Comment by rashmichandrashekar** [comment]
@danielqsj - Checking back, pls let me know when the next version of the chart will be released, thanks!

**Comment by rashmichandrashekar** [comment]
@danielqsj - gentle ping, pls let me know when the next version might be released. Thanks!

**Comment by danielqsj** [comment]
LGTM, thanks @rashmichandrashekar

**Pull request merged**
