### PR TITLE
offset/lag collect use all partition if consumer group is not Stable

### LINKED ISSUE #244: kafka_consumergroup_current_offset not show up
kafka_exporter-1.3.1.linux-amd64.tar.gz,
kafka version is 2.4.1
the problem is:   kafka_consumergroup_current_offset  and kafka_consumergroup_lag not display in metrics page, 
any suggest?

### PR DESCRIPTION
**Pull request by iamgd67**
from #220 I introduce a feature to use assigned partitions instead of all partitions to fetch groups offsets, this is good, especially when the broker has many partitions. 
but it causes death or self-managed (use `assign` instead of `subscribe`) groups lag/offset not showing too, while dead consumer's offset/lag is very useful too, it should be better that we fetch all partitions when the consumer group state is not stable.

thanks @scholzj and @Kaali09 for pointing this problem out.
this resolves #244 #252 #237

### CODE REVIEW

**Comment by zbialik** [comment]
Would appreciate a quick release of this as we are looking to bring in this exporter specifically for these consumergroup metrics. 

Thanks for the help!

**Comment by iamgd67** [comment]
@zbialik before this got merged and released, a workaround may be using version < 1.3.1, like 1.3.0

**Comment by danielqsj** [comment]
@iamgd67 LGTM

**Comment by double-yaya** [comment]
I have the same issues,
kafka exporter: 1.4.2
kafka:2.8.1
@danielqsj

**Comment by Kaali09** [comment]
@double-yaya You can use v1.3.0 kafka version for time being. This will resolve your issue.

**Comment by Kaali09** [comment]
@iamgd67 @danielqsj Thank you for the fix.

**Comment by double-yaya** [comment]
> @double-yaya You can use v1.3.0 kafka exporter version for time being. This will resolve your issue.
 use 1.3.0 have the same question ,offset/lag collect is not  Stable
kafka exporter: 1.4.2
kafka:2.8.1

**Comment by double-yaya** [comment]
@Kaali09   use 1.3.2 the same issue

**Pull request merged**
