### PR TITLE
Rebased fork1 (#213)

### PR DESCRIPTION
**Pull request by alesj**
Rebased #213 and added minor things for easy Travis release.

### CODE REVIEW

**Comment by brunsgaard** [comment]
👍

**Comment by brunsgaard** [comment]
Are there a plan/timeline for merging this?

**Comment by Skunnyk** [comment]
There is a lot of changes in this MR (some completely unrelated to performances), so I guess it's really hard for @danielqsj to do a review :/

**Comment by danielqsj** [comment]
@alesj @brunsgaard there is another PR https://github.com/danielqsj/kafka_exporter/pull/238 which looks like based on this PR and do more enhancement. We should compare and make these two PRs together.

**Comment by danielqsj** [comment]
thanks @alesj , Due to the large difference between this patch and master branch, so I cherry-picked from here, and released v1.4.1. @ALL, please have a try.

**Pull request closed without merging**
